language: node_js
node_js:
  - 'stable'
install: npm install
services:
  - postgresql
before_script:
  - psql -c 'create database test_mypharm;' -U postgres
  - psql -c "CREATE USER calebmugisha WITH PASSWORD null;" -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script: npm test
after_success: npm run coverage
