version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: calebmugisha
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: test_mypharm
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: calebmugisha

          working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn
      - run:
          key: setting up env key
          command: echo "export COVERALLS_TOKEN=$COVERALLS_TOKEN" >> $BASH_ENV
      - run: yarn global add sequelize-cli
      - run: yarn global add pg
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # Wait for Postgres connection to open.
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: yarn run migrate

      # run tests
      - run: yarn run test
      - run: yarn run coverage
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
